version: '3.1'
services:
  backend:
    build: '.'
    ports:
      - '8080:80'
  frontend:
    image: python:3.8-slim
    entrypoint: python -m http.server --directory /public
    volumes:
      - './docs:/public'
